// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdkiatdffzsgngnxkzny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpka2lhdGRmZnpzZ25nbnhrem55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjYzMjYsImV4cCI6MjA2NTIwMjMyNn0._MyJDId8PaP7-Xel40GFHklM0Ag95WtVeKhLZWesxxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);